import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_illustrations.dart';
import '../../../core/providers/group_provider.dart';
import '../../../core/providers/members_provider.dart';
import '../../../core/providers/contributions_provider.dart';
import '../../../core/utils/date_helpers.dart';
import '../../../shared/widgets/app_button.dart';

class GenerateReportScreen extends ConsumerStatefulWidget {
  final String groupId;
  final String reportType;
  const GenerateReportScreen({required this.groupId, this.reportType = 'Monthly Summary', super.key});

  @override
  ConsumerState<GenerateReportScreen> createState() => _GenerateReportScreenState();
}

class _GenerateReportScreenState extends ConsumerState<GenerateReportScreen> {
  bool _isGenerating = false;
  int _selectedMonth = DateTime.now().month;
  int _selectedYear = DateTime.now().year;

  Future<void> _generatePdf() async {
    setState(() => _isGenerating = true);
    try {
      final group = await ref.read(currentGroupProvider(widget.groupId).future);
      final members = await ref.read(membersProvider(widget.groupId).future);
      final contributions = await ref.read(contributionsProvider(widget.groupId).future);

      if (group == null) return;

      final pdf = pw.Document();
      final totalCollected = contributions.where((c) => c.status.name == 'paid').fold<double>(0, (s, c) => s + c.amount);
      final pendingCount = contributions.where((c) => c.status.name == 'pending').length;

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (ctx) => [
            pw.Header(text: group.name, level: 0, textStyle: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
            pw.Paragraph(text: 'Report generated: ${DateHelpers.formatDateTime(DateTime.now())}'),
            pw.SizedBox(height: 20),
            pw.Header(text: 'Summary', level: 1),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Members: ${group.stats.totalMembers}'),
                pw.Text('Active: ${members.where((m) => m.status == 'active').length}'),
              ],
            ),
            pw.SizedBox(height: 20),
            pw.Header(text: 'Income', level: 1),
            pw.TableHelper.fromTextArray(
              headers: ['Description', 'Amount'],
              data: [
                ['Total Collected', 'KES ${totalCollected.toStringAsFixed(0)}'],
                ['Pending', 'KES ${(pendingCount * 500).toStringAsFixed(0)}'],
              ],
            ),
            pw.SizedBox(height: 20),
            pw.Header(text: 'Recent Contributions', level: 1),
            pw.TableHelper.fromTextArray(
              headers: ['Member', 'Type', 'Amount', 'Date'],
              data: contributions.take(20).map((c) => [
                c.memberName,
                c.typeName,
                'KES ${c.amount.toStringAsFixed(0)}',
                DateHelpers.formatDate(c.paidAt),
              ]).toList(),
            ),
            pw.SizedBox(height: 20),
            pw.Text('Generated by Ledger — The record your community keeps forever.',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
          ],
        ),
      );

      final dir = await getTemporaryDirectory();
      final file = File('${dir.path}/Ledger_Report_${DateTime.now().millisecondsSinceEpoch}.pdf');
      await file.writeAsBytes(await pdf.save());

      if (mounted) {
        await Share.shareXFiles([XFile(file.path)]);
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Report generated and shared')));
      }
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isGenerating = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(title: const Text('Generate Report')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Center(
              child: SizedBox(
                width: 140, height: 140,
                child: SvgPicture.network(
                  AppIllustrations.report,
                  fit: BoxFit.contain,
                  placeholderBuilder: (_) => Container(
                    width: 80, height: 80,
                    decoration: BoxDecoration(
                      gradient: AppColors.primaryGradient,
                      borderRadius: BorderRadius.circular(20),
                    ),
                    child: const Icon(Icons.description, size: 40, color: Colors.white),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 24),
            const Text('Report Type', style: TextStyle(fontWeight: FontWeight.w600)),
            const SizedBox(height: 8),
            Text(widget.reportType, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: AppColors.primary)),
            const SizedBox(height: 32),
            const Text('Period', style: TextStyle(fontWeight: FontWeight.w600)),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  child: DropdownButtonFormField<int>(
                    initialValue: _selectedMonth,
                    items: List.generate(12, (i) => DropdownMenuItem(value: i + 1, child: Text(DateFormat('MMMM').format(DateTime(2024, i + 1))))),
                    onChanged: (v) => setState(() => _selectedMonth = v!),
                    decoration: const InputDecoration(labelText: 'Month'),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: DropdownButtonFormField<int>(
                    initialValue: _selectedYear,
                    items: List.generate(5, (i) => DropdownMenuItem(value: DateTime.now().year - i, child: Text('${DateTime.now().year - i}'))),
                    onChanged: (v) => setState(() => _selectedYear = v!),
                    decoration: const InputDecoration(labelText: 'Year'),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 32),
            AppButton(
              label: 'Generate Report',
              icon: Icons.description,
              onPressed: _generatePdf,
              isLoading: _isGenerating,
            ),
            const SizedBox(height: 16),
            OutlinedButton.icon(
              onPressed: _isGenerating ? null : _generatePdf,
              icon: const Icon(Icons.picture_as_pdf),
              label: const Text('Preview & Print'),
            ),
            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }
}
